//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int id { get; set; }
        public Nullable<int> khachhangid { get; set; }
        public Nullable<int> sanphamid { get; set; }
        public int soluong { get; set; }
        public System.DateTime ngaymua { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
